language: ruby

rvm:
  - 2.6
  - 2.7
  - ruby-head

before_install:
  - gem update --system "3.1.2"
  - sudo apt-get update -qq
  - sudo apt-get install -qq libunwind8-dev

script: bundle exec rake compile && bundle exec rake test:mpdecimal
